"""Create SearchLog table

Revision ID: 0cca4ca84269
Revises: 
Create Date: 2025-11-11 23:15:59.086436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cca4ca84269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('top_text', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_log_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_log_created_at'))

    op.drop_table('search_log')
    # ### end Alembic commands ###
